In [1]:
#Packages And Librarys
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
#Taking Data
x=np.array([[5,2],[7,4],[11,9],[15,12],[19,17]])
y=np.array([7,3,5,19,6])

In [4]:
#Fitting Model
model=LinearRegression().fit(x,y)

In [5]:
#Predicitng Y values for Given X values (b0+(b1*x))
y_pre=model.predict(x)

In [6]:
print("Predict Score: ",model.score(x,y_pre))
print("Normal Score : ",model.score(x,y))

Predict Score:  1.0
Normal Score :  0.6313446969696973


In [7]:
#Differnce Between Y predict and Given Y
print(y_pre)
print(y)

[ 5.84848485  7.75757576  1.68181818 15.39393939  9.31818182]
[ 7  3  5 19  6]


In [8]:
#Rechecking With Formula (b0+(b1*x))
print("b0: ",model.intercept_)
print("b1: ",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x,axis=1)
print("Rechecked Y predict Values : ",y_rc)

b0:  -28.606060606060538
b1:  [10.84848485 -9.89393939]
Rechecked Y predict Values :  [ 5.84848485  7.75757576  1.68181818 15.39393939  9.31818182]


In [10]:
#Predicitng Y values for Given X_new values (b0+(b1*x))
x_new=np.array([12,13,14,15,16,18,19,20,21,22]).reshape(-1,2)
y_new=model.predict(x_new)
print(x_new)
print(y_new)

[[12 13]
 [14 15]
 [16 18]
 [19 20]
 [21 22]]
[-27.04545455 -25.13636364 -33.12121212 -20.36363636 -18.45454545]


In [11]:
print("New Predict Score: ",model.score(x_new,y_new))

New Predict Score:  1.0
