In [1]:
import numpy as np
n=np.random.randint(0,10,5)
n

array([3, 2, 8, 1, 3])

In [2]:
nn=np.random.normal(1,2,5)
nn

array([ 0.83383342,  2.12468677,  3.47077259, -1.27106176, -0.43888315])

In [3]:
x=np.arange(15,55)
x

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

In [4]:
x[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [5]:
f=np.arange(1,11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
f[5:]

array([ 6,  7,  8,  9, 10])

In [7]:
matrix_3x4=np.arange(0,12).reshape(3,4)
matrix_3x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
for i in matrix_3x4:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [9]:
for x in np.nditer(matrix_3x4):
    print(x,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [10]:
print(f,end="<br>")

[ 1  2  3  4  5  6  7  8  9 10]<br>

In [11]:
vector=np.linspace(10,50,5)
vector

array([10., 20., 30., 40., 50.])

In [12]:
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
a[(a>=9)&(a<=15)]*=-1
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [14]:
h=np.linspace(1,11,5)
h

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [15]:
y=h*n
y

array([ 3. ,  7. , 48. ,  8.5, 33. ])

In [16]:
n

array([3, 2, 8, 1, 3])

In [17]:
f=np.arange(10,22).reshape(3,4)
f

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [18]:
f.shape

(3, 4)

In [19]:
f[1,2]

16

In [20]:
d=np.identity(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
dd=np.zeros([3,3,3,3])
dd

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [22]:
i=0
for i in range(0,3,1):
    dd[i,i]=1

In [23]:
dd

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [24]:
fd=np.ones([10,10])
fd

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
fd[1:-1,1:-1]=0
fd

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
g=np.zeros([5,5])
g

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
i=0
for i in range(0,5,1):
    g[i,i]=i+1
g

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [28]:
jj=np.diag(np.arange(4))
jj

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [29]:
i=np.zeros((4,4))
i

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
for l in range(0,4,1):
    for j in range(0,4,2):
        if(l%2==0):
            i[l,j]=1
        else:
            i[l,j+1]=1
i

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [31]:
ii=np.zeros((4,4))
ii[1::2,1::2]=1
ii[0::2,0::2]=1
ii

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [32]:
iu=np.random.random((3,3,3))
iu

array([[[0.24082898, 0.56068335, 0.54166909],
        [0.39252243, 0.32865467, 0.72445218],
        [0.68802453, 0.82068871, 0.85756007]],

       [[0.62904302, 0.01492239, 0.33137402],
        [0.97229655, 0.27252806, 0.13248512],
        [0.5828766 , 0.86457188, 0.58018679]],

       [[0.50663693, 0.76890984, 0.35443345],
        [0.08746132, 0.27558279, 0.86290236],
        [0.47386363, 0.04640546, 0.65795654]]])

In [33]:
np.sum(iu)

13.569520740193337

In [34]:
uu=np.arange(0,12).reshape(3,4)
uu

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
np.sum(uu,axis=0)

array([12, 15, 18, 21])

In [36]:
np.sum(uu,axis=1)

array([ 6, 22, 38])

In [37]:
x=np.array([4,5])
y=np.array([7,10])
np.dot(x,y)

78

In [38]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(11,20).reshape(3,3)

In [39]:
np.dot(x,y)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [40]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
y

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
v=np.array([1,1,0])
r=np.empty_like(x)

In [43]:
r

array([[ 543515987, 1869835329,  538976266],
       [ 757935392,  757935405,  538970669],
       [1868767264, 1701998701, 1918858099]])

In [44]:
for p in range(3):
    r[p,:]=x[p,:]+v

In [45]:
r

array([[2, 3, 3],
       [5, 6, 6],
       [8, 9, 9]])

In [46]:
import os
a=np.arange(20)
np.save("temp.npy",a)
if os.path.exists("temp.npy"):
    x2=np.load("temp.npy")
    print(np.array_equal(a,x2))

True


In [47]:
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
y=np.arange(21,30)
np.savez("tempz.npz",a=a,y=y)
with np.load("tempz.npz") as data:
    x3=data['a']
    y3=data['y']
    print(x3)
    print(y3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[21 22 23 24 25 26 27 28 29]


In [50]:
x2=np.load("tempz.npz")

In [51]:
x2

In [52]:
x=np.arange(12).reshape(4,3)
header="col1 col2 col3"
np.savetxt("tempp.txt",x,fmt="%d",header=header)
result=np.loadtxt("tempp.txt")
result

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [53]:
x4=x3.tobytes()

In [54]:
x4

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

In [55]:
x6=np.frombuffer(x4,dtype=x3.dtype)
x6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
x3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
a=[1,1,2]
x=np.array(a)
a3=x.tolist()
print(a == a3)

True


In [58]:
n=np.zeros(10)
d=np.unique(n)

In [59]:
d

array([0.])