In [1]:
import numpy as np

In [2]:
a = np.arange(6)
# range from 0 to n(ex=6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
y=np.zeros(23)
y
#array of zeros upto n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [4]:
x=np.ones(23)
x
#array of ones upto n

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [5]:
s=np.empty(2)
s

array([ 1.32774111e+289, -9.12379517e-049])