In [5]:
#Packages And Librarys
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [6]:
#Taking Data
x=np.array([5,2,4,14,4]).reshape(-1,1)
y=np.array([7,3,5,19,6])

In [7]:
#Fitting Model
model=LinearRegression().fit(x,y)

In [22]:
#Predicitng Y values for Given X values (b0+(b1*x))
y_pre=model.predict(x)

In [23]:
print("Predict Score: ",model.score(x,y_pre))
print("Normal Score : ",model.score(x,y))

Predict Score:  1.0
Normal Score :  0.9966920045045045


In [24]:
#Differnce Between Y predict and Given Y
print(y_pre)
print(y)

[ 6.92792793  2.90765766  5.58783784 18.98873874  5.58783784]
[ 7  3  5 19  6]


In [33]:
#Rechecking With Formula (b0+(b1*x))
print("b0: ",model.intercept_)
print("b1: ",model.coef_)
y_rc=model.intercept_+np.sum(model.coef_*x,axis=1)
print("Rechecked Y predict Values : ",y_rc)

b0:  0.22747747747747749
b1:  [1.34009009]
Rechecked Y predict Values :  [ 6.92792793  2.90765766  5.58783784 18.98873874  5.58783784]


In [26]:
#Predicitng Y values for Given X_new values (b0+(b1*x))
x_new=np.array([12,13,14,15,16]).reshape(-1,1)
y_new=model.predict(x_new)
print(x_new)
print(y_new)

[[12]
 [13]
 [14]
 [15]
 [16]]
[16.30855856 17.64864865 18.98873874 20.32882883 21.66891892]


In [27]:
print("New Predict Score: ",model.score(x_new,y_new))

New Predict Score:  1.0
